mode: restart
blueprint:
  name: Presence Control with Timer
  description: >
    Управление режимами присутствия с учётом движения, выключателей, двери и времени суток.
    Автоматически переключает статус "Кто-то дома", "Никого нет", "Длительное отсутствие".<br>
    ver. 1.0
  domain: automation
  input:
    presence_entity:
      name: Список "Присутствие"
      description: input_select с режимами присутствия
      selector:
        entity:
          domain: input_select

    motion_sensors:
      name: Датчики движения
      description: Сенсоры движения (occupancy)
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: occupancy

    switches:
      name: Выключатели
      description: Переключатели для фиксации активности
      selector:
        entity:
          multiple: true
          domain: binary_sensor

    door_sensor:
      name: Датчик двери
      description: off — закрыта, on — открыта
      selector:
        entity:
          domain: binary_sensor
          device_class: door

    time_of_day_entity:
      name: Список "Время суток"
      description: input_select с текущим временем суток (Утро, День, Вечер, Ночь)
      selector:
        entity:
          domain: input_select

    presence_timer:
      name: Таймер присутствия
      description: Отсчёт до режима "Никого нет"
      selector:
        entity:
          domain: timer

    no_presence_delay:
      name: Задержка до "Никого нет" (минуты)
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

    long_absence_days:
      name: Порог "Длительное отсутствие" (дни)
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: days

variables:
  var_time_of_day: !input time_of_day_entity

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    id: motion_trigger

  - platform: state
    entity_id: !input switches
    from: "off"
    to: "on"
    id: switch_on_trigger

  - platform: state
    entity_id: !input switches
    from: "on"
    to: "off"
    id: switch_off_trigger

  - platform: state
    entity_id: !input door_sensor
    from: "on"
    to: "off"
    id: door_trigger

  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input presence_timer
    id: timer_finished_trigger

  - platform: state
    entity_id: !input presence_entity
    to: "Никого нет"
    for:
      days: !input long_absence_days
    id: long_absence_trigger

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_trigger
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input presence_entity
              option: "Кто-то дома"
          - service: timer.cancel
            data:
              entity_id: !input presence_timer

      - conditions:
          - condition: trigger
            id:
              - switch_on_trigger
              - switch_off_trigger
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input presence_entity
              option: "Кто-то дома"
          - service: timer.cancel
            data:
              entity_id: !input presence_timer

      - conditions:
          - condition: trigger
            id: door_trigger
          - condition: template
            value_template: >
              {{ states(var_time_of_day) != 'Ночь' }}
        sequence:
          - service: timer.start
            data:
              entity_id: !input presence_timer
              duration:
                minutes: !input no_presence_delay

      - conditions:
          - condition: trigger
            id: timer_finished_trigger
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input presence_entity
              option: "Никого нет"

      - conditions:
          - condition: trigger
            id: long_absence_trigger
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input presence_entity
              option: "Длительное отсутствие"
