blueprint:
  name: Time of Day Control
  description: Управление временем суток с приоритетом ночи по времени и вечера после дня.<br>ver. 0.4b
  domain: automation
  input:
    time_of_day_entity:
      name: Список "Время суток"
      selector:
        entity:
          domain: input_select
    weekday_morning_time:
      name: Время начала дня (будни)
      default: "08:00"
      selector:
        time:
    weekend_morning_time:
      name: Время начала дня (выходные)
      default: "09:30"
      selector:
        time:
    night_time:
      name: Время начала ночи
      default: "23:00"
      selector:
        time:

trigger:
  - platform: sun
    event: sunrise
    id: sunrise
  - platform: time
    at: !input weekday_morning_time
    id: weekday_morning
  - platform: time
    at: !input weekend_morning_time
    id: weekend_morning
  - platform: sun
    event: sunset
    id: sunset
  - platform: time
    at: !input night_time
    id: night_time

action:
  - choose:
      - conditions:
          - condition: trigger
            id: sunrise
          - condition: template
            value_template: >
              {{ states(input.time_of_day_entity) not in ['День','Вечер','Ночь'] }}
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input time_of_day_entity
              option: Рассвет
              
      - conditions:
          - condition: trigger
            id: weekday_morning
          - condition: template
            value_template: "{{ now().weekday() < 5 }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input time_of_day_entity
              option: День
              
      - conditions:
          - condition: trigger
            id: weekend_morning
          - condition: template
            value_template: "{{ now().weekday() >= 5 }}"
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input time_of_day_entity
              option: День
              
      - conditions:
          - condition: trigger
            id: sunset
          - condition: state
            entity_id: !input time_of_day_entity
            state: День
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input time_of_day_entity
              option: Вечер
              
      - conditions:
          - condition: trigger
            id: night_time
        sequence:
          - service: input_select.select_option
            data:
              entity_id: !input time_of_day_entity
              option: Ночь